# dataset
path: /home/spfa/dataset/kitti
dataset: kitti
category_name: Car  # ['Car', 'Van', 'Pedestrian', 'Cyclist']
point_dim: 3
train_split: train
valid_split: valid
test_split: test tiny
coordinate_mode: velodyne

# dataloader
full_area: False
rand_distortion_range: 0.3
search_area_offset: 2
template_size: 512
search_size: 1024
workers: 12
box_enlarge_scale: 1.25

random_sample: False
num_candidates: 1

# model
addnorm_drop: 0.2
n_head: 8
dgn_k: 5
att_k: 5
motion_k: 5
rpn_k: 5

# train
checkpoint: ./checkpoint
batch_size: 32
epoch: 60
pretrain:
optimizer: adam
lr: 0.001
check_val_every_n_epoch: 1
save_last: False

# loss
box_weight: 0.5
cla_weight: 0.5
